/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cmjdproject.learner.view.manager.internels;

import cmjdproject.learner.controller.RegisterController;
import cmjdproject.learner.controller.SheduleController;
import cmjdproject.learner.controller.ShedulepartController;
import cmjdproject.learner.db.DBConnection;
import cmjdproject.learner.models.SheduleMod;
import cmjdproject.learner.models.ShedulepartMod;
import cmjdproject.learner.other.LoadtoCombo;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.border.TitledBorder;


/*
 *
 * @author oshanz
 */
public class AssignToShedule extends javax.swing.JInternalFrame {

    private boolean a, b, c;
    private String selectedrid;
    private String day1;
    private String day2;
    private String day3;
    private String selectdate1;
    private String selectdate1time;
    private String selectdate1amount;
    private String selectdate2;
    private String selectdate2time;
    private String selectdate2amount;

    /**
     * Creates new form AssignToShedule
     */
    public AssignToShedule() {
        initComponents();

        submitButon.setEnabled(false);

        buttonGroup1.add(day1rb1);
        buttonGroup1.add(day1rb2);
        buttonGroup1.add(day1rb3);
        buttonGroup1.add(day1rb4);

        buttonGroup2.add(day2rb1);
        buttonGroup2.add(day2rb2);
        buttonGroup2.add(day2rb3);
        buttonGroup2.add(day2rb4);

        buttonGroup3.add(day3rb1);
        buttonGroup3.add(day3rb2);
        buttonGroup3.add(day3rb3);
        buttonGroup3.add(day3rb4);
        try {
            Properties properties = new Properties();
            properties.load(new FileInputStream("inforamation.properties"));
            String maxallowed = properties.getProperty("maxpershift");
            maxpost.setText(maxallowed);
        } catch (FileNotFoundException ex) {
            errorReport(ex);
        } catch (IOException ex) {
            errorReport(ex);
        }


        try {
            new LoadtoCombo().load(searchComboBox);
            //  new ComboSearch().setSearchableCombo(searchComboBox, true, "");
//            new AutoCompletion(searchComboBox);
//            new SwingSorter().sortComboBox(searchComboBox);
            //  jPanel1.setBorder(new TitledBorder("efaef"));
        } catch (SQLException ex) {
            errorReport(ex);
        } catch (ClassNotFoundException ex) {
            errorReport(ex);
        } catch (FileNotFoundException ex) {
            errorReport(ex);
        } catch (IOException ex) {
            errorReport(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        searchComboBox = new javax.swing.JComboBox();
        nicTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        submitButon = new javax.swing.JButton();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        daypanel3 = new javax.swing.JPanel();
        day3rb3 = new javax.swing.JRadioButton();
        day3rb1 = new javax.swing.JRadioButton();
        day3rb2 = new javax.swing.JRadioButton();
        day3rb4 = new javax.swing.JRadioButton();
        day33 = new javax.swing.JLabel();
        day34 = new javax.swing.JLabel();
        day32 = new javax.swing.JLabel();
        day31 = new javax.swing.JLabel();
        daypanel2 = new javax.swing.JPanel();
        day2rb3 = new javax.swing.JRadioButton();
        day2rb1 = new javax.swing.JRadioButton();
        day2rb2 = new javax.swing.JRadioButton();
        day2rb4 = new javax.swing.JRadioButton();
        day23 = new javax.swing.JLabel();
        day24 = new javax.swing.JLabel();
        day22 = new javax.swing.JLabel();
        day21 = new javax.swing.JLabel();
        daypanel1 = new javax.swing.JPanel();
        day1rb3 = new javax.swing.JRadioButton();
        day1rb1 = new javax.swing.JRadioButton();
        day1rb2 = new javax.swing.JRadioButton();
        day1rb4 = new javax.swing.JRadioButton();
        day13 = new javax.swing.JLabel();
        day14 = new javax.swing.JLabel();
        day12 = new javax.swing.JLabel();
        day11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lab3 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        sex = new javax.swing.JCheckBox();
        maxlable = new javax.swing.JLabel();
        maxpost = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        searchComboBox.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                searchComboBoxMouseWheelMoved(evt);
            }
        });
        searchComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                searchComboBoxPopupMenuWillBecomeVisible(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                searchComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        searchComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchComboBoxItemStateChanged(evt);
            }
        });
        searchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboBoxActionPerformed(evt);
            }
        });
        searchComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchComboBoxPropertyChange(evt);
            }
        });
        searchComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchComboBoxKeyReleased(evt);
            }
        });

        nicTextField.setEditable(false);

        nameTextField.setEditable(false);

        jLabel5.setText("NIC");

        jLabel6.setText("Name");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Days"));

        submitButon.setText("Submit");
        submitButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButonActionPerformed(evt);
            }
        });

        date1.setText(" ");

        date2.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date1)
                .addGap(18, 18, 18)
                .addComponent(date2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 32, Short.MAX_VALUE)
                .addComponent(submitButon)
                .addContainerGap())
        );

        jPanel5.setBorder(null);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel5MouseReleased(evt);
            }
        });
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel5MouseMoved(evt);
            }
        });
        jPanel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel5PropertyChange(evt);
            }
        });
        jPanel5.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jPanel5VetoableChange(evt);
            }
        });

        daypanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Day"));

        day3rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3rb3ActionPerformed(evt);
            }
        });

        day3rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3rb1ActionPerformed(evt);
            }
        });

        day3rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3rb2ActionPerformed(evt);
            }
        });

        day3rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3rb4ActionPerformed(evt);
            }
        });

        day33.setText("          ");

        day34.setText("          ");

        day32.setText("          ");

        day31.setText("          ");

        javax.swing.GroupLayout daypanel3Layout = new javax.swing.GroupLayout(daypanel3);
        daypanel3.setLayout(daypanel3Layout);
        daypanel3Layout.setHorizontalGroup(
            daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daypanel3Layout.createSequentialGroup()
                .addGroup(daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daypanel3Layout.createSequentialGroup()
                        .addComponent(day3rb1)
                        .addGap(18, 18, 18)
                        .addComponent(day31))
                    .addGroup(daypanel3Layout.createSequentialGroup()
                        .addComponent(day3rb2)
                        .addGap(18, 18, 18)
                        .addComponent(day32))
                    .addGroup(daypanel3Layout.createSequentialGroup()
                        .addComponent(day3rb3)
                        .addGap(18, 18, 18)
                        .addComponent(day33))
                    .addGroup(daypanel3Layout.createSequentialGroup()
                        .addComponent(day3rb4)
                        .addGap(18, 18, 18)
                        .addComponent(day34)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        daypanel3Layout.setVerticalGroup(
            daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daypanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day31)
                    .addComponent(day3rb1))
                .addGap(18, 18, 18)
                .addGroup(daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day3rb2)
                    .addComponent(day32))
                .addGap(18, 18, 18)
                .addGroup(daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day3rb3)
                    .addComponent(day33))
                .addGap(18, 18, 18)
                .addGroup(daypanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day3rb4)
                    .addComponent(day34))
                .addContainerGap())
        );

        daypanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Day"));

        day2rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2rb3ActionPerformed(evt);
            }
        });

        day2rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2rb1ActionPerformed(evt);
            }
        });

        day2rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2rb2ActionPerformed(evt);
            }
        });

        day2rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2rb4ActionPerformed(evt);
            }
        });

        day23.setText("          ");

        day24.setText("          ");

        day22.setText("          ");

        day21.setText("          ");

        javax.swing.GroupLayout daypanel2Layout = new javax.swing.GroupLayout(daypanel2);
        daypanel2.setLayout(daypanel2Layout);
        daypanel2Layout.setHorizontalGroup(
            daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daypanel2Layout.createSequentialGroup()
                .addGroup(daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daypanel2Layout.createSequentialGroup()
                        .addComponent(day2rb1)
                        .addGap(18, 18, 18)
                        .addComponent(day21))
                    .addGroup(daypanel2Layout.createSequentialGroup()
                        .addComponent(day2rb2)
                        .addGap(18, 18, 18)
                        .addComponent(day22))
                    .addGroup(daypanel2Layout.createSequentialGroup()
                        .addComponent(day2rb3)
                        .addGap(18, 18, 18)
                        .addComponent(day23))
                    .addGroup(daypanel2Layout.createSequentialGroup()
                        .addComponent(day2rb4)
                        .addGap(18, 18, 18)
                        .addComponent(day24)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        daypanel2Layout.setVerticalGroup(
            daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daypanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day21)
                    .addComponent(day2rb1))
                .addGap(18, 18, 18)
                .addGroup(daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day2rb2)
                    .addComponent(day22))
                .addGap(18, 18, 18)
                .addGroup(daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day2rb3)
                    .addComponent(day23))
                .addGap(18, 18, 18)
                .addGroup(daypanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day2rb4)
                    .addComponent(day24))
                .addContainerGap())
        );

        daypanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Day"));

        day1rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1rb3ActionPerformed(evt);
            }
        });

        day1rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1rb1ActionPerformed(evt);
            }
        });

        day1rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1rb2ActionPerformed(evt);
            }
        });

        day1rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1rb4ActionPerformed(evt);
            }
        });

        day13.setText("          ");

        day14.setText("          ");

        day12.setText("          ");

        day11.setText("          ");

        javax.swing.GroupLayout daypanel1Layout = new javax.swing.GroupLayout(daypanel1);
        daypanel1.setLayout(daypanel1Layout);
        daypanel1Layout.setHorizontalGroup(
            daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daypanel1Layout.createSequentialGroup()
                .addGroup(daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daypanel1Layout.createSequentialGroup()
                        .addComponent(day1rb1)
                        .addGap(18, 18, 18)
                        .addComponent(day11))
                    .addGroup(daypanel1Layout.createSequentialGroup()
                        .addComponent(day1rb2)
                        .addGap(18, 18, 18)
                        .addComponent(day12))
                    .addGroup(daypanel1Layout.createSequentialGroup()
                        .addComponent(day1rb3)
                        .addGap(18, 18, 18)
                        .addComponent(day13))
                    .addGroup(daypanel1Layout.createSequentialGroup()
                        .addComponent(day1rb4)
                        .addGap(18, 18, 18)
                        .addComponent(day14)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        daypanel1Layout.setVerticalGroup(
            daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daypanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day11)
                    .addComponent(day1rb1))
                .addGap(18, 18, 18)
                .addGroup(daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day1rb2)
                    .addComponent(day12))
                .addGap(18, 18, 18)
                .addGroup(daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day1rb3)
                    .addComponent(day13))
                .addGap(18, 18, 18)
                .addGroup(daypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day1rb4)
                    .addComponent(day14))
                .addContainerGap())
        );

        lab3.setText("2.30 pm");

        lab4.setText("4.30 pm");

        lab2.setText("11.30 am");

        lab1.setText("9.30 am");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab1)
                .addGap(18, 18, 18)
                .addComponent(lab2)
                .addGap(18, 18, 18)
                .addComponent(lab3)
                .addGap(18, 18, 18)
                .addComponent(lab4)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daypanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daypanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daypanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daypanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(daypanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(daypanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sex.setText("sex");
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });

        maxlable.setText("Max per shift");

        maxpost.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sex)
                                        .addGap(10, 10, 10))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maxlable, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maxpost, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxpost)
                    .addComponent(maxlable))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButonActionPerformed
        // TODO add your handling code here:
        //
        // System.out.println(selectdate1 + " " + selectdate2amount + " " + selectdate1time + " " + selectedrid);
        int updateShedules = -1;
        int remove = -1;
        int setshedule = -1;
        int setParticipationinfo = -1;

        try {
            DBConnection.getDirectConnection().setAutoCommit(false);
            /**
             * Get Previous Participation Days from participation table
             */
            ArrayList<ShedulepartMod> paricipationInfo = new ShedulepartController().getparicipationInfo(selectedrid);

            for (ShedulepartMod shedulepartMod : paricipationInfo) {
                /**
                 * reduce one from each days for schedule table
                 */
                System.out.println("-1");
                updateShedules = new SheduleController().updateShedules(shedulepartMod.getDayofweek(), shedulepartMod.getTime());
                if (updateShedules <= 0) {
                    JOptionPane.showMessageDialog(null, "Action Faild at update shedules(-1)");
                }
                remove = 100;
            }

            /**
             * Remove Previous participation days from participation table
             */
            if (remove == 100) {
                remove = new ShedulepartController().remove(selectedrid);
                if (remove <= 0) {
                    JOptionPane.showMessageDialog(this, "participation reset in't done");
                }
            }


            ArrayList<SheduleMod> arrayList = new ArrayList<SheduleMod>();
            SheduleMod sheduleMod = new SheduleMod(null, selectdate1, selectdate1time, Integer.parseInt(selectdate1amount) + 1);
            SheduleMod sheduleMod1 = new SheduleMod(null, selectdate2, selectdate2time, Integer.parseInt(selectdate2amount) + 1);
            arrayList.add(sheduleMod);
            arrayList.add(sheduleMod1);
            /**
             * Update new students amount of schedule table
             */
            setshedule = new SheduleController().setshedule(arrayList);
            if (setshedule <= 0) {
                JOptionPane.showMessageDialog(null, "Action Faild at update shedules(+1) " + setshedule);
            }

            ArrayList<ShedulepartMod> arrayList1 = new ArrayList<ShedulepartMod>();
            arrayList1.add(new ShedulepartMod(selectedrid, null, selectdate1, selectdate1time));
            arrayList1.add(new ShedulepartMod(selectedrid, null, selectdate2, selectdate2time));
            /**
             * Insert new Participation dates
             */
            setParticipationinfo = new ShedulepartController().setParticipationinfo(arrayList1);
            if (setshedule <= 0) {
                JOptionPane.showMessageDialog(null, "Action Faild at assign to participation " + setParticipationinfo);
            }
            if (setParticipationinfo > 0 && setshedule > 0) {
                DBConnection.getDirectConnection().commit();
                JOptionPane.showMessageDialog(this, "Done");
            } else {
                JOptionPane.showMessageDialog(this, "Action Failed");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Action faild " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Action faild " + ex.getMessage());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Action faild " + ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Action faild " + ex.getMessage());
        } finally {
            try {
                DBConnection.getDirectConnection().setAutoCommit(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
            }
        }



    }//GEN-LAST:event_submitButonActionPerformed

    private void searchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboBoxActionPerformed
        // TODO add your handling code here:
        // if(searchComboBox.get)


        cleardata();

        if (searchComboBox.getSelectedItem() == null | searchComboBox.getItemAt(0) == null) {
        } else {
            String[] split = searchComboBox.getSelectedItem().toString().split(",\\s*");
            // System.out.println(split[0]+"  "+split[1]);
            nicTextField.setText(split[0]);
            nameTextField.setText(split[1]);
            int parseInt = Integer.parseInt(split[0].substring(2, 5));
            if (parseInt < 500) {
                sex.setSelected(true);
                sex.setText("male");
            } else {
                sex.setSelected(false);
                sex.setText("female");
            }
        }


        loadinfo();
    }//GEN-LAST:event_searchComboBoxActionPerformed

    private void searchComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboBoxItemStateChanged

    private void searchComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchComboBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboBoxPropertyChange

    private void searchComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_searchComboBoxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboBoxPopupMenuWillBecomeInvisible

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
        if (sex.isSelected()) {
            sex.setText("male");
        } else {
            sex.setText("female");
        }
        loadinfo();
    }//GEN-LAST:event_sexActionPerformed

    private void day3rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3rb4ActionPerformed
        buttonGroup3ok(day34, day3rb4, lab4);          // TODO add your handling code here:
    }//GEN-LAST:event_day3rb4ActionPerformed

    private void searchComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_searchComboBoxPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboBoxPopupMenuWillBecomeVisible

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseReleased

    private void jPanel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseMoved
        // TODO add your handling code here:
//        if (buttonGroup1.getSelection() != null) {
//
//            boolean selected = buttonGroup1.getSelection().isSelected();
//            System.out.println(selected);
//        } else {
//        }
    }//GEN-LAST:event_jPanel5MouseMoved

    private void jPanel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5PropertyChange

    private void jPanel5VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jPanel5VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5VetoableChange

    private void day1rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1rb1ActionPerformed
        // TODO add your handling code here:
        buttonGroup1ok(day11, day1rb1, lab1);

    }//GEN-LAST:event_day1rb1ActionPerformed

    private void day1rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1rb2ActionPerformed
        // TODO add your handling code here:
        buttonGroup1ok(day12, day1rb2, lab2);
    }//GEN-LAST:event_day1rb2ActionPerformed

    private void day1rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1rb3ActionPerformed
        buttonGroup1ok(day13, day1rb3, lab3);
        // TODO add your handling code here:
    }//GEN-LAST:event_day1rb3ActionPerformed

    private void day1rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1rb4ActionPerformed
        buttonGroup1ok(day14, day1rb4, lab4);        // TODO add your handling code here:
    }//GEN-LAST:event_day1rb4ActionPerformed

    private void day2rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2rb1ActionPerformed
        buttonGroup2ok(day21, day2rb1, lab1);        // TODO add your handling code here:
    }//GEN-LAST:event_day2rb1ActionPerformed

    private void day2rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2rb2ActionPerformed
        buttonGroup2ok(day22, day2rb2, lab2);         // TODO add your handling code here:
    }//GEN-LAST:event_day2rb2ActionPerformed

    private void day2rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2rb3ActionPerformed
        buttonGroup2ok(day23, day2rb3, lab3);         // TODO add your handling code here:
    }//GEN-LAST:event_day2rb3ActionPerformed

    private void day2rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2rb4ActionPerformed
        buttonGroup2ok(day24, day2rb4, lab4);         // TODO add your handling code here:
    }//GEN-LAST:event_day2rb4ActionPerformed

    private void day3rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3rb1ActionPerformed
        buttonGroup3ok(day31, day3rb1, lab1);         // TODO add your handling code here:
    }//GEN-LAST:event_day3rb1ActionPerformed

    private void day3rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3rb2ActionPerformed
        buttonGroup3ok(day32, day3rb2, lab2);          // TODO add your handling code here:
    }//GEN-LAST:event_day3rb2ActionPerformed

    private void day3rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3rb3ActionPerformed
        buttonGroup3ok(day33, day3rb3, lab3);          // TODO add your handling code here:
    }//GEN-LAST:event_day3rb3ActionPerformed

    private void searchComboBoxMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_searchComboBoxMouseWheelMoved
        // TODO add your handling code here:
        // MouseWheelListener[] mouseMotionListeners = searchComboBox.setMouseWheelListeners();
        //
        //        try {
        //            int wheelRotation = evt.getWheelRotation();
        //            int selectedIndex = searchComboBox.getSelectedIndex();
        //            int itemCount = searchComboBox.getItemCount();
        //            System.out.println(""+selectedIndex+" "+itemCount);
        //
        //
        //            if (selectedIndex <= 0) {
        //               searchComboBox.setSelectedIndex(searchComboBox.getSelectedIndex() + wheelRotation);
        //            }
        //
        //            System.out.println(""+selectedIndex);
        //
        //        } catch (IllegalArgumentException e) {
        //            System.out.println("err");
        //        }
        //
    }//GEN-LAST:event_searchComboBoxMouseWheelMoved

    private void searchComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchComboBoxKeyReleased
        // TODO add your handling code here:
////        boolean selectWithKeyChar = searchComboBox.selectWithKeyChar(evt.getKeyChar());
////        if (selectWithKeyChar) {
////            Object selectedItem = searchComboBox.getSelectedItem();
////            System.out.println(selectedItem);
////        } else {
////            // searchComboBox.getModel().
////        }
    }//GEN-LAST:event_searchComboBoxKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel day11;
    private javax.swing.JLabel day12;
    private javax.swing.JLabel day13;
    private javax.swing.JLabel day14;
    private javax.swing.JRadioButton day1rb1;
    private javax.swing.JRadioButton day1rb2;
    private javax.swing.JRadioButton day1rb3;
    private javax.swing.JRadioButton day1rb4;
    private javax.swing.JLabel day21;
    private javax.swing.JLabel day22;
    private javax.swing.JLabel day23;
    private javax.swing.JLabel day24;
    private javax.swing.JRadioButton day2rb1;
    private javax.swing.JRadioButton day2rb2;
    private javax.swing.JRadioButton day2rb3;
    private javax.swing.JRadioButton day2rb4;
    private javax.swing.JLabel day31;
    private javax.swing.JLabel day32;
    private javax.swing.JLabel day33;
    private javax.swing.JLabel day34;
    private javax.swing.JRadioButton day3rb1;
    private javax.swing.JRadioButton day3rb2;
    private javax.swing.JRadioButton day3rb3;
    private javax.swing.JRadioButton day3rb4;
    private javax.swing.JPanel daypanel1;
    private javax.swing.JPanel daypanel2;
    private javax.swing.JPanel daypanel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel maxlable;
    private javax.swing.JLabel maxpost;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nicTextField;
    private javax.swing.JComboBox searchComboBox;
    private javax.swing.JCheckBox sex;
    private javax.swing.JButton submitButon;
    // End of variables declaration//GEN-END:variables

    private void filltable() {

        if (sex.isSelected()) {

            day1 = "monday";

            day2 = "wednesday";

            day3 = "friday";
        } else {
            day1 = "tuesday";

            day2 = "thursday";

            day3 = "saturday";
        }
        //   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try {
            ArrayList<Integer> sheduleinfo = new SheduleController().getSheduleinfo(day1, day2, day3);

            setamount(sheduleinfo);


            daypanel1.setBorder(new TitledBorder(day1));
            daypanel2.setBorder(new TitledBorder(day2));
            daypanel3.setBorder(new TitledBorder(day3));

//            for (Integer integer : sheduleinfo) {
//                model.addRow(new Object[]{integer});
//            }



        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AssignToShedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setamount(ArrayList<Integer> sheduleinfo) {
        int parseInt = Integer.parseInt(maxpost.getText());
        if (sheduleinfo.get(0) >= parseInt) {
            day11.setText(sheduleinfo.get(0) + "");
            day11.setForeground(Color.red);
        } else {
            day11.setForeground(Color.BLACK);
            day11.setText(sheduleinfo.get(0) + "");
        }
        if (sheduleinfo.get(1) >= parseInt) {
            day12.setText(sheduleinfo.get(1) + "");
            day12.setForeground(Color.red);
        } else {
            day12.setForeground(Color.BLACK);
            day12.setText(sheduleinfo.get(1) + "");
        }
        if (sheduleinfo.get(2) >= parseInt) {
            day13.setText(sheduleinfo.get(2) + "");
            day13.setForeground(Color.red);
        } else {
            day13.setForeground(Color.BLACK);
            day13.setText(sheduleinfo.get(2) + "");
        }
        if (sheduleinfo.get(3) >= parseInt) {
            day14.setText(sheduleinfo.get(3) + "");
            day14.setForeground(Color.red);
        } else {
            day14.setForeground(Color.BLACK);
            day14.setText(sheduleinfo.get(3) + "");
        }
        if (sheduleinfo.get(4) >= parseInt) {
            day21.setText(sheduleinfo.get(4) + "");
            day21.setForeground(Color.red);
        } else {
            day21.setForeground(Color.BLACK);
            day21.setText(sheduleinfo.get(4) + "");
        }
        if (sheduleinfo.get(5) >= parseInt) {
            day22.setText(sheduleinfo.get(5) + "");
            day22.setForeground(Color.red);
        } else {
            day22.setForeground(Color.BLACK);
            day22.setText(sheduleinfo.get(5) + "");
        }
        if (sheduleinfo.get(6) >= parseInt) {
            day23.setText(sheduleinfo.get(6) + "");
            day23.setForeground(Color.red);
        } else {
            day23.setForeground(Color.BLACK);
            day23.setText(sheduleinfo.get(6) + "");
        }
        if (sheduleinfo.get(7) >= parseInt) {
            day24.setText(sheduleinfo.get(7) + "");
            day24.setForeground(Color.red);
        } else {
            day24.setForeground(Color.BLACK);
            day24.setText(sheduleinfo.get(7) + "");
        }
        if (sheduleinfo.get(8) >= parseInt) {
            day31.setText(sheduleinfo.get(8) + "");
            day31.setForeground(Color.red);
        } else {
            day31.setForeground(Color.BLACK);
            day31.setText(sheduleinfo.get(8) + "");
        }
        if (sheduleinfo.get(9) >= parseInt) {
            day32.setText(sheduleinfo.get(9) + "");
            day32.setForeground(Color.red);
        } else {
            day32.setForeground(Color.BLACK);
            day32.setText(sheduleinfo.get(9) + "");
        }
        if (sheduleinfo.get(10) >= parseInt) {
            day33.setText(sheduleinfo.get(10) + "");
            day33.setForeground(Color.red);
        } else {
            day33.setForeground(Color.BLACK);
            day33.setText(sheduleinfo.get(10) + "");
        }
        if (sheduleinfo.get(11) >= parseInt) {
            day34.setText(sheduleinfo.get(11) + "");
            day34.setForeground(Color.red);
        } else {
            day34.setForeground(Color.BLACK);
            day34.setText(sheduleinfo.get(11) + "");
        }
//            day11.setText(sheduleinfo.get(0)+"");
//            day12.setText(sheduleinfo.get(1)+"");
//            day13.setText(sheduleinfo.get(2)+"");
//            day14.setText(sheduleinfo.get(3)+"");
//            day21.setText(sheduleinfo.get(4)+"");
//            day22.setText(sheduleinfo.get(5)+"");
//            day23.setText(sheduleinfo.get(6)+"");
//            day24.setText(sheduleinfo.get(7)+"");
//            day31.setText(sheduleinfo.get(8)+"");
//            day32.setText(sheduleinfo.get(9)+"");
//            day33.setText(sheduleinfo.get(10)+"");
//            day34.setText(sheduleinfo.get(11)+"");

    }

    private void buttonGroup1ok(JLabel amount, JRadioButton jrb, JLabel time) {
        if (c && b) {

            cleardata();
        } else {
            if (a) {
                //   a = false;
                //    buttonGroup1.clearSelection();
                cleardata();
            }
            if (buttonGroup1.getSelection() != null && buttonGroup1.getSelection().isSelected()) {
                setdata(day1, time.getText(), amount.getText());
                a = true;
            }
        }


    }

    private void buttonGroup2ok(JLabel amount, JRadioButton jrb, JLabel time) {

        if (a && c) {

            cleardata();
        } else {
            if (b) {
                //  b = false;
                //  buttonGroup2.clearSelection();
                cleardata();
            }
            if (buttonGroup2.getSelection() != null && buttonGroup2.getSelection().isSelected()) {
                setdata(day2, time.getText(), amount.getText());
                b = true;
            }

        }

    }

    private void buttonGroup3ok(JLabel amount, JRadioButton jrb, JLabel time) {
        if (a && b) {

            cleardata();
        } else {
            if (c) {
                // c = false;
                // buttonGroup3.clearSelection();
                cleardata();
            }
            if (buttonGroup3.getSelection() != null && buttonGroup3.getSelection().isSelected()) {
                setdata(day3, time.getText(), amount.getText());
                c = true;
            }

        }

    }

    private void setdata(String day, String time, String amount) {
//        String ampm = null;
        // System.out.println(time+" "+9.30+"");
//        if (Double.valueOf(time)==9.30 |Double.valueOf(time)==11.30 ) {
//            ampm = time + " am";
//        } else if(Double.valueOf(time)==2.30 |Double.valueOf(time)==4.30) {
//            ampm = time + " pm";
//        }

        selectdate2 = selectdate1;
        selectdate2time = selectdate1time;
        selectdate2amount = selectdate1amount;

        selectdate1 = day;
        selectdate1time = time;
        selectdate1amount = amount;

        date2.setText(date1.getText());
        date1.setText(day + " , " + time);
        if (date1.getText().equalsIgnoreCase(date2.getText())) {

            date2.setText("");
            date1.setText("");
        }

        if (date2.getText() != null & !"".equals(date2.getText())) {
            submitButon.setEnabled(true);
        }
    }

    private void cleardata() {

        buttonGroup1.clearSelection();
        a = false;
        buttonGroup3.clearSelection();
        c = false;
        buttonGroup2.clearSelection();
        b = false;

        selectdate1 = null;
        selectdate1amount = null;
        selectdate1time = null;
        selectdate2 = null;
        selectdate2amount = null;
        selectdate2time = null;

        date1.setText("");
        date2.setText("");

        submitButon.setEnabled(false);
    }

    private void errorReport(Exception ex) {
        JOptionPane.showMessageDialog(this, "Cannot load Details");
    }

    private void loadinfo() {

        cleardata();

        try {
            // TODO add your handling code here:
            String ristrationid = RegisterController.getRistrationid(nicTextField.getText());
            if (ristrationid != null) {
                selectedrid = ristrationid;
            } else {
                JOptionPane.showMessageDialog(this, "Candidate Isn't Registerd");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer");
        }
        // System.out.println(selectedrid);

        filltable();
    }
}
