/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cmjdproject.learner.view.manager.internels;

import cmjdproject.learner.controller.CourceController;
import cmjdproject.learner.other.CurrencyConvert;
import cmjdproject.learner.other.LoadtoCombo;
import cmjdproject.learner.other.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author oshanz
 */
public class Candidate extends javax.swing.JInternalFrame {

    private CardLayout cardLayout;
    private boolean mc, dp, tw, bus;

    /**
     * Creates new form Candidate
     */
    public Candidate(String formName) {
        //   System.out.println(formName);
        initComponents();
        //   setDefaultCloseOperation(EXIT_ON_CLOSE);
        try {
            new LoadtoCombo().load(loadIdAndName);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
        }

        jPanel1.setLayout(cardLayout);
        cardLayout = new CardLayout();
        jPanel1.setLayout(cardLayout);

        jPanel1.add(addCandidate, "1");
        jPanel1.add(register, "2");


        //  cardLayout.first(jPanel1);
        CandidateTabbedPane.removeTabAt(1);
        CandidateTabbedPane.addTab("Add Candidate", jPanel1);
        CandidateTabbedPane.addTab("Update Information", jPanel2);
        // if (formName.equalsIgnoreCase("Manager Form")) {
        //      CandidateTabbedPane.add(new DeleteCandidate());
        //   }

        //cardLayout.show(jPanel1, "1");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CandidateTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        busCB = new javax.swing.JCheckBox();
        dualpurposeCB = new javax.swing.JCheckBox();
        motorcycleCB = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        treewhCB = new javax.swing.JCheckBox();
        backButton = new javax.swing.JButton();
        pricelable = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        loadIdAndName = new javax.swing.JComboBox();
        regNic = new javax.swing.JTextField();
        regName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addCandidate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        telephoneLable = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        candiName = new javax.swing.JTextField();
        nameLable = new javax.swing.JLabel();
        nidLable = new javax.swing.JLabel();
        addressLable = new javax.swing.JLabel();
        candiNid = new javax.swing.JTextField();
        vxSpinner = new javax.swing.JSpinner();
        nextButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        updateCombobox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        CandidateTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CandidateTabbedPaneMouseReleased(evt);
            }
        });
        CandidateTabbedPane.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CandidateTabbedPanePropertyChange(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jButton1.setText("Submit");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Price");

        busCB.setText("Bus (D)");
        busCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busCBActionPerformed(evt);
            }
        });

        dualpurposeCB.setText("Dual Purpose (B)");
        dualpurposeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dualpurposeCBActionPerformed(evt);
            }
        });

        motorcycleCB.setText("Motorcycle (A)");
        motorcycleCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorcycleCBActionPerformed(evt);
            }
        });

        treewhCB.setText("Tree-wheeler (B1)");
        treewhCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treewhCBActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        pricelable.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        pricelable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pricelable.setText(" ");

        loadIdAndName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadIdAndNameActionPerformed(evt);
            }
        });

        regNic.setEditable(false);
        regNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNicActionPerformed(evt);
            }
        });
        regNic.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                regNicPropertyChange(evt);
            }
        });

        regName.setEditable(false);

        jLabel4.setText("Name");

        jLabel2.setText("NIC");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(regNic, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(regName, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loadIdAndName, 0, 635, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loadIdAndName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(registerLayout.createSequentialGroup()
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(registerLayout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(pricelable, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dualpurposeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(motorcycleCB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(treewhCB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(busCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 231, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(registerLayout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(motorcycleCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dualpurposeCB)
                .addGap(16, 16, 16)
                .addComponent(treewhCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busCB)
                .addGap(76, 76, 76)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pricelable))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(register, "card3");

        jLabel1.setText("Add Candidate");

        telephoneLable.setText("Telephone");

        telephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneTextFieldActionPerformed(evt);
            }
        });
        telephoneTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telephoneTextFieldFocusLost(evt);
            }
        });
        telephoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telephoneTextFieldKeyReleased(evt);
            }
        });

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        addressTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(addressTextArea);

        candiName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candiNameActionPerformed(evt);
            }
        });
        candiName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                candiNameFocusLost(evt);
            }
        });
        candiName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                candiNameKeyReleased(evt);
            }
        });

        nameLable.setText("Name");

        nidLable.setText("NID");

        addressLable.setText("Address");

        candiNid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candiNidActionPerformed(evt);
            }
        });
        candiNid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                candiNidFocusLost(evt);
            }
        });
        candiNid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                candiNidKeyReleased(evt);
            }
        });

        vxSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"V", "X"}));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nidLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(candiName, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candiNid, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(vxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(telephoneLable)
                                .addGap(6, 6, 6)
                                .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(addressLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candiName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candiNid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nidLable)
                    .addComponent(vxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLable)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telephoneLable)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCandidateLayout = new javax.swing.GroupLayout(addCandidate);
        addCandidate.setLayout(addCandidateLayout);
        addCandidateLayout.setHorizontalGroup(
            addCandidateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCandidateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCandidateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCandidateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(addCandidateLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCandidateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addCandidateLayout.setVerticalGroup(
            addCandidateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCandidateLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(nextButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(addCandidate, "card3");

        CandidateTabbedPane.addTab("Add Candidate", jPanel1);

        jLabel5.setText("Name");

        jTextField3.setEditable(false);

        jLabel7.setText("Telephone");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel8.setText("Address");

        jButton2.setText("Update");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateCombobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 291, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(updateCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        CandidateTabbedPane.addTab("Update Information", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidateTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidateTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CandidateTabbedPanePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CandidateTabbedPanePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidateTabbedPanePropertyChange

    private void CandidateTabbedPaneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CandidateTabbedPaneMouseReleased
        // TODO add your handling code here:
        if (CandidateTabbedPane.getModel().getSelectedIndex() == 1) {
            try {
                new LoadtoCombo().load(updateCombobox);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Contact Developer " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_CandidateTabbedPaneMouseReleased

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:



        cardLayout.show(jPanel1, "2");
        regName.setText(candiName.getText());
        regNic.setText(candiNid.getText() + vxSpinner.getValue());

    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        cardLayout.show(jPanel1, "1");
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String address = addressTextArea.getText().replace('\n', ',');
        // System.out.println(address);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadIdAndNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadIdAndNameActionPerformed
        // TODO add your handling code here:

        if (loadIdAndName.getSelectedItem() != null) {
            String[] split = loadIdAndName.getSelectedItem().toString().split(",\\s*");

            regNic.setText(split[0]);
            regName.setText(split[1]);
        }
    }//GEN-LAST:event_loadIdAndNameActionPerformed

    private void regNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNicActionPerformed

    private void regNicPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_regNicPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_regNicPropertyChange

    private void candiNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_candiNameKeyReleased
        // TODO add your handling code here:
        System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() != 110 & evt.getKeyCode() != 46) {
            candiName.setForeground(Color.BLACK);
            candiName.setText(Validation.validateLetters(candiName.getText(), evt));
        } else {
            candiName.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "name isnt valid");
        }

    }//GEN-LAST:event_candiNameKeyReleased

    private void candiNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_candiNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_candiNameFocusLost

    private void candiNidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_candiNidKeyReleased
        // TODO add your handling code here:
        candiNid.setText(Validation.validateInt(candiNid.getText(), evt.getKeyChar(), 9));
    }//GEN-LAST:event_candiNidKeyReleased

    private void addressTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextAreaKeyReleased
        // TODO add your handling code here:
        //  String validateLetters = Validation.validateLetters(addressTextArea.getText().toString(), evt);
        addressTextArea.setText(Validation.validateAddress(addressTextArea.getText().replace('\n', ','), evt).replace(',', '\n'));
    }//GEN-LAST:event_addressTextAreaKeyReleased

    private void telephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneTextFieldActionPerformed
        // TODO add your handling code here:
        boolean equalsIgnoreCase = candiName.getText().equalsIgnoreCase("");
        boolean equalsIgnoreCase1 = candiNid.getText().equalsIgnoreCase("");

        if (equalsIgnoreCase && equalsIgnoreCase1) {
            nextButton.setEnabled(false);
        } else {
            nextButton.setEnabled(true);
        }
    }//GEN-LAST:event_telephoneTextFieldActionPerformed

    private void telephoneTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneTextFieldKeyReleased
        // TODO add your handling code here:

        telephoneTextField.setText(Validation.validateInt(telephoneTextField.getText(), evt.getKeyChar(), 10));
    }//GEN-LAST:event_telephoneTextFieldKeyReleased

    private void telephoneTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telephoneTextFieldFocusLost
        // TODO add your handling code here:
        boolean validatePhone = Validation.validatePhone(telephoneTextField.getText());
        if (!validatePhone) {
            JOptionPane.showMessageDialog(this, "no may not valid");
            backButtonActionPerformed(null);

        }
    }//GEN-LAST:event_telephoneTextFieldFocusLost

    private void candiNidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_candiNidFocusLost
        // TODO add your handling code here:
        if (!(candiNid.getText().equalsIgnoreCase("")) & !(candiNid.getText() == null)) {
            String substring = candiNid.getText().substring(0, 2);
            String substring2 = "19".concat(substring);
            int get = Calendar.getInstance().get(Calendar.YEAR);
            int parseInt = Integer.parseInt(substring2);
            //System.out.println(parseInt + " " + (get));
            if (!(get >= (parseInt + 18))) {
                JOptionPane.showMessageDialog(this, "NIC may wrong or Age isnt Valid");
            }
        }
    }//GEN-LAST:event_candiNidFocusLost

    private void candiNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candiNameActionPerformed
        // TODO add your handling code here:
        candiNid.requestFocus(true);
    }//GEN-LAST:event_candiNameActionPerformed

    private void candiNidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candiNidActionPerformed
        // TODO add your handling code here:
        addressTextArea.requestFocus(true);
    }//GEN-LAST:event_candiNidActionPerformed

    private void motorcycleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorcycleCBActionPerformed
        // TODO add your handling code here:
        if (motorcycleCB.isSelected()) {
            mc = true;
        } else {
            mc = false;
        }

        setprice();
    }//GEN-LAST:event_motorcycleCBActionPerformed

    private void dualpurposeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dualpurposeCBActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (dualpurposeCB.isSelected()) {
            dp = true;
        } else {
            dp = false;
        }

        setprice();
    }//GEN-LAST:event_dualpurposeCBActionPerformed

    private void treewhCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treewhCBActionPerformed
        // TODO add your handling code here:
        if (treewhCB.isSelected()) {
            tw = true;
        } else {
            tw = false;
        }

        setprice();
    }//GEN-LAST:event_treewhCBActionPerformed

    private void busCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busCBActionPerformed
        // TODO add your handling code here:
        if (busCB.isSelected()) {
            bus = true;
        } else {
            bus = false;
        }

        setprice();
    }//GEN-LAST:event_busCBActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CandidateTabbedPane;
    private javax.swing.JPanel addCandidate;
    private javax.swing.JLabel addressLable;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox busCB;
    private javax.swing.JTextField candiName;
    private javax.swing.JTextField candiNid;
    private javax.swing.JCheckBox dualpurposeCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox loadIdAndName;
    private javax.swing.JCheckBox motorcycleCB;
    private javax.swing.JLabel nameLable;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel nidLable;
    private javax.swing.JLabel pricelable;
    private javax.swing.JTextField regName;
    private javax.swing.JTextField regNic;
    private javax.swing.JPanel register;
    private javax.swing.JLabel telephoneLable;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JCheckBox treewhCB;
    private javax.swing.JComboBox updateCombobox;
    private javax.swing.JSpinner vxSpinner;
    // End of variables declaration//GEN-END:variables

    private void setprice() {
        if (mc) {
            getandsetprice("c02");
        }
        if (dp) {
            getandsetprice("c01");
        }
        if (tw) {
            getandsetprice("c04");
        }
        if (bus) {
            getandsetprice("c03");

        }
        if (dp & mc) {
            getandsetprice("c05");
        }
        if (dp & tw) {
            getandsetprice("c06");
        }
        if (mc & tw) {
            getandsetprice("c07");
        }
        if (dp & tw & mc) {
            getandsetprice("c08");
        }
        if (!dp & !tw & !mc) {
            pricelable.setText("");
        }
        if (bus & dp) {
            JOptionPane.showMessageDialog(this, "Invalid");
            pricelable.setText("");
        }





        //   System.out.println(dp + " " + mc + " " + tw + " " + bus);

    }

    private void getandsetprice(String cid) {
        try {

            pricelable.setText(new CurrencyConvert().convert(new CourceController().getfees(cid)));

//            if (pricelable.getText().equalsIgnoreCase("")) {
//                pricelable.setText(new CourceController().getfees(cid) + "");
//            }

        } catch (SQLException ex) {
            Logger.getLogger(Candidate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Candidate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Candidate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Candidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
