/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cmjdproject.learner.view.manager.internels;

import cmjdproject.learner.other.Validation;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author oshanz
 */
public class TestandSheduleProperties extends javax.swing.JDialog {

    private Properties properties;

    /**
     * Creates new form TestandSheduleProperties
     */
    public TestandSheduleProperties(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        properties = new Properties();
        try {
            properties.load(new FileInputStream("inforamation.properties"));
            shifttext.setText(properties.getProperty("maxpershift"));
            feetest.setText(properties.getProperty("testfee"));
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + " Contact Developer");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + " Contact Developer");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shifttext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        feetest = new javax.swing.JTextField();
        shiftsavebutton = new javax.swing.JButton();
        feeSaveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Number of Candidates per Shift");

        shifttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shifttextActionPerformed(evt);
            }
        });

        jLabel2.setText("Test Fee");

        feetest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feetestActionPerformed(evt);
            }
        });

        shiftsavebutton.setText("Save");
        shiftsavebutton.setEnabled(false);
        shiftsavebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftsavebuttonActionPerformed(evt);
            }
        });

        feeSaveButton.setText("Save");
        feeSaveButton.setEnabled(false);
        feeSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(shifttext))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(feetest, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shiftsavebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(feeSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(shifttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shiftsavebutton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(feetest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeSaveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shiftsavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftsavebuttonActionPerformed
        // TODO add your handling code here:
        properties.setProperty("maxpershift", shifttext.getText());
        try {
            properties.store(new FileOutputStream("inforamation.properties"), null);
            JOptionPane.showMessageDialog(this, "Done");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + " Contact Developer");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + " Contact Developer");
        }
    }//GEN-LAST:event_shiftsavebuttonActionPerformed

    private void feeSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeSaveButtonActionPerformed
        // TODO add your handling code here:
        properties.setProperty("testfee", feetest.getText());
        try {
            properties.store(new FileOutputStream("inforamation.properties"), null);
            JOptionPane.showMessageDialog(this, "Done");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + " Contact Developer");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() + " Contact Developer");
        }
    }//GEN-LAST:event_feeSaveButtonActionPerformed

    private void shifttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shifttextActionPerformed
        // TODO add your handling code here
        boolean validateInt = Validation.validateInt(shifttext.getText());
        if (validateInt) {
            shifttext.setEnabled(false);
            shiftsavebutton.setEnabled(true);

        }
    }//GEN-LAST:event_shifttextActionPerformed

    private void feetestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feetestActionPerformed
        // TODO add your handling code here:
        boolean validateInt = Validation.validateInt(feetest.getText());
        if (validateInt) {
            feetest.setEnabled(false);
            feeSaveButton.setEnabled(true);

        }
    }//GEN-LAST:event_feetestActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feeSaveButton;
    private javax.swing.JTextField feetest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton shiftsavebutton;
    private javax.swing.JTextField shifttext;
    // End of variables declaration//GEN-END:variables
}
